### ISSUE TITLE
How many  records at a time load or read .

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile-api#11]

**Comment by alexanderon** [comment]
@cviacmob , Can you please elaborate more? You can have records as per your requirement by providing thee parameter value for the offset and limit.

**Comment by bunny-oogbox** [comment]
Reopen issue if your problem not resolved.
Thanks.

**Comment by cviacmob** [comment]
Hi, i load to more than 3000 records can not be load serachread method still stopping the load action. this my below code what can i do.

   OdooFields fields = new OdooFields();
        fields.addAll("name", "address1", "address2", "address3", "pin_code", "mobile_no", "bank_id", "bank_branch_id", "account_no", "old_id", "transporter_code", "pan_no");
        int offset = 0;
        int limit = 100000;
        String sorting = "";
        client.searchRead("transporter.master", null, fields, offset, limit, sorting, new IOdooResponse() {
            @Override
            public void onResult(OdooResult result) {
                OdooRecord[] records = result.getRecords();

                try {
                    for (OdooRecord record : records) {
                        TransPortDb masterDb = new TransPortDb(record.getString("name"), record.getString("address1"), record.getString("address2"), record.getString("address3"), record.getString("pin_code"), record.getString("mobile_no"), record.getString("bank_id"), record.getString("bank_branch_id"), record.getString("account_no"), record.getString("old_id"), record.getString("transporter_code"), record.getString("pan_no"));
                        masterDb.save();
                    }
                } finally {
                    //  ActiveAndroid.endTransaction();
                }
            }
        });
