### ISSUE TITLE
Hug Data Read or load very slowly how to solved

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile-api#18]
How to fast data load in server database , 
Example for i load the 3000 records but slowly read the database the blew code.

 ODomain domain = new ODomain();
        domain.add("state", "=", "draft");
        OdooFields fields = new OdooFields();
        fields.addAll("id", "doc_forty_id", "ryot_name", "season_id", "uom_id", "plant_type_id", "ryot_number", "cane_variety_id", "division_id", "crop_type_id", "estimated_setts", "section_name", "plot_name", "setts_type_id", "active",
                "name", "planting_date", "village_name", "display_name", "nursery_fitness_certificate");
        int offset = 0;
        int limit = 100000;
        String sorting = "";
        client.searchRead("doc.forty.for.sdo", null, fields, offset, limit, sorting, new IOdooResponse() {
            @Override
            public void onResult(OdooResult result) {
                OdooRecord[] records = result.getRecords();
                for (OdooRecord record : records) {
             
                }
            }
        });
    }

**Comment by bunny-oogbox** [comment]
Hello @cviacmob 

By default, if you are showing records in ``ListView`` or ``GridView`` or with ``RecyclerView`` you know that at the same time maximum you can see 15-20 records on the screen. 

If you are requesting huge data, it take more time to complete request because it based on your network. Better, if you can limit your data by setting ``limit`` and ``offset`` in api call and load next bunch of records with offset when user scroll your view to bottom.

If you don't want to use manuall offset and limit, you can use ``RequestBuilder`` class which handle auto request to next limited records if any.

See Example: (Suppose we have 1000 records in res.partner and we want to load 50 record at the time and when user scroll page to bottom it load next 100 )
```java
OdooClient client = ....
DataResponse dataResponse = RequestBuilder.init(client, "res.partner")
        .setLimit(100)
        .withDomain(new ODomain().add("customer", "=", true))
        .withFields("id", "name")
        .withSorting("name")
        .build();

dataResponse.getRecords(new IOdooRecords() {
    @Override
    public void onRecords(OdooRecords records) {
        List<OdooRecord> newLoadedRecords = records.getNewRecords();
        // TODO: Add records to your view

       // you can call request next when user reach at the bottom of screen
       // you need to store OdooRecords object globally.
        if (records.hasNext()) {
            // has records
            records.requestNext();
        }
    }
});
```

Depending your fields, you can change limit of records to request.

Hope this will solve your issue.
Thanks.

**Comment by cviacmob** [comment]
Hi, But I am not using Listview , Gridview, RecyclerView . they are using tableview for pagination using more than 20table it will take the minimum 5min loading the data. how to is i solve?

**Comment by bunny-oogbox** [comment]
@cviacmob  How much data are you showing at the same time? And don't fetch all 20 tables data at once. When you need to show data to the user, just request with limited records (as shown in my previous comment), when user press next/previous just request another bunch of records with offset/limit set.

**Comment by cviacmob** [comment]
@bunny-oogbox  first time login to i fetch all data more than 20 tables. all data to load data saved from Local database .

**Comment by bunny-oogbox** [comment]
@cviacmob 

Okay, so you are syncing all the data (20 tables) for the first time login so you can access it offline.

But IMHO, You should only sync Related data, like many2one records which are used for your main model and are not continuosly updated (Such as category, types). And just sync it in the background so the user doesn't need to wait for the sync to complete. 

For example, If you are creating Project Application than your main model is ``project.project`` and ``project.task``. But if you know, ``Project`` will not always changed or updated but its task are created/updated. 

At the login time, you need to sync projects only, and task related models ``project.tags``, ``res.partner`` 

You can not always sync everything, and yes it take time if you do. Make list of models you need before user start to use your application and sync them at the time of login (by showing message **Preparing your account**), and when user open perticular screen, just sync that required model. (Like if user opening tasks, just sync tasks)

There are many ways to complete this stuff, its depending on you how you treat with data and screens.

Hope this will help you.
Thanks.
OOGBox Mobile Team.
