### ISSUE TITLE
Need to upload csv file to a module

### ISSUE THREAD

**Issue by razorahul** [oogbox/odoo-mobile-api#19]
There is a web side implementation for the import which works in 3 stages: upload, map, and import. Is there any way I can pre-configure the mapping part and upload through the android side.

**Comment by bunny-oogbox** [comment]
Hello @razorahul 
You need to create a list of records from CSV file and call ``create()`` method of api one by one or if you are using odoo **12.0+**, Odoo support multiple record create at once. You can create more than one record in single api call

```java
OdooClient client = ....
List<JSONObject> recordsList = .....
OArguments args = new OArguments();
args.add(recordsList);
client.call_kw("your.model", "create", args, new IOdooResponse() {
    @Override
    public void onResult(OdooResult result) {
        // response with ids list in same sequence of recordList
    }
});
// Supports in Odoo 12.0+ only
```

Hope this will help.
Thanks.
