### ISSUE TITLE
Odoo V12 Search read

### ISSUE THREAD

**Issue by chiragchauhan1073** [oogbox/odoo-mobile-api#20]
Hello, After taking latest odoo v12 pull from Git, i am able to connet with Odoo but search read is not working.
i am getting
" POST /web/dataset/call_kw/res.users/read HTTP/1.1" 404 - 1 0.004 0.007"  in Odoo Logs and
"Odoo Version: 13.0alpha1+e
2019-02-23 07:53:07.258 22911-23001/E/Volley: [544] BasicNetwork.performRequest: Unexpected response code 404 for http://........../web/dataset/call_kw/res.users/read" in android Logs.
Here is the Login infomation
OdooUser : {uid=2, companyId=1, partnerId=3, name='Mitchell Admin', username='admin', lang='en_US', tz='Asia/Kolkata', database='test', fcmProjectId='false', sessionId='null', isSuperuser=false, odooVersion=OdooVersion{server_version='13.0alpha1', is_enterprise=false, server_version= [13.0, 0.0, 0.0, alpha, 1.0]}}

**Comment by bunny-oogbox** [comment]
Hello @chiragchauhan1073 
I think you are on **master** branch instead **12.0** 
The version **13.0alpha1** is for master branch.

You can check version in Settings dashboard by connecting to the instance on the browser.

**Comment by bunny-oogbox** [comment]
If you still facing this the issue. Feel free to reopen the issue.
Thank.s
