### ISSUE TITLE
Adding attachment to a product.

### ISSUE THREAD

**Issue by razorahul** [oogbox/odoo-mobile-api#21]
I have tried using the implementation in the class `IrAttachment` to upload an attachment to a product. But I am confused. I don't see any documentation related to it. Can anyone please help on this.

**Comment by bunny-oogbox** [comment]
Hello @razorahul 

Can you explain your problem in detail? Wich ``IrAttachment`` implementation you have done and for the product are you trying to set **image** of a product or you need to attach files on product record?

**Comment by koz01** [comment]
Hello @razorahul 
Are you fix your problem?

**Comment by bunny-oogbox** [comment]
Please feel free to re-open the issue if your problem not resolved.
Closing issue for now.
Thanks.
