### ISSUE TITLE
Call kw

### ISSUE THREAD

**Issue by sathyaventhan** [oogbox/odoo-mobile-api#8]
Hi am impressed odooo .i am facing some issue like .call kw we didt get callback method of result

**Comment by pranasabda** [comment]
OOGBox is very helpful, but I have the same issue too when using call_kw for using "confirm button" method in RoQ (Request of Quotation) at Purchase.

**Comment by bunny-oogbox** [comment]
Hello @sathyaventhan  @pranasabda  
Can you please elaborate your case when its not response result back?

**Comment by pranasabda** [comment]
Hello, @bunny-oogbox  thanks for the response, 
i just new using Odoo 10 and try to follow the documentation of OOGBox lib

when I try to use the Calling model methods "call_kw",
 I want to call method button of "button_confrim" on RFQ (Request For Quotation) at Purchase Apps Odoo 10.

![photo_2018-07-09_16-29-22](https://user-images.githubusercontent.com/2637442/42442636-65f855c6-8395-11e8-87d2-f18d61639a53.jpg)

This is my code :
`public void confirmOrderPurchaseOdoo() {

        String PO_id = ""+ getPO_Id;
        String order_line = ""+getPO_Id+1; 

        OArguments arguments = new OArguments();
        arguments.add(PO_id);
        arguments.add(order_line);

        client.call_kw("purchase.order", "button_confirm", arguments, new IOdooResponse() {
            @Override
            public void onResult(OdooResult result) {
                // response
                Log.d("TAG", "onResult: " + result);
            }
        });
    }
`
and i got error like this : 
E/a: ERROR: 
		     **** Database fetch misses ids (u'45') and has extra ids (45), may be caused by a type incoherence in a previous request
     		None ****
     		on http://182.23.20.101:38069/web/dataset/call_kw/purchase.order/button_confirm [9286]

Sometimes the error got this : 
E/a: ERROR: 
     		**** The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

     		(Document type: purchase.order, Operation: read)
     		None ****
     		on http://182.23.20.101:38069/web/dataset/call_kw/purchase.order/button_confirm [8521]

that is my problem I don't know where I got wrong, and thanks for your response, this library is very helpful, 

thank you :+1:

**Comment by bunny-oogbox** [comment]
Hello @pranasabda 

When you using ``call_kw`` remember that, first parameter always list of **ids** (Record ids) and second is User context.

In your example code, You are passing ``PO_id`` as string and not in list of ids.
The second parameter is not context of user (you can just pass empty JSON there).

So your code should be,
```diff
    OArguments arguments = new OArguments();
-   arguments.add(PO_id);
-   arguments.add(order_line);
+   arguments.add(Arrays.asList(PO_id));
+   arguments.add(new JSONObject());

    client.call_kw("purchase.order", "button_confirm", arguments, new IOdooResponse() {
        @Override
        public void onResult(OdooResult result) {
            // response
            Log.d("TAG", "onResult: " + result);
        }
    });
```

Here, ``OArguments`` are parameter of your method. And when calling method with ``@api.multi``  remember that its working on recordsets and you need to pass first parameter as list of record ids which will create record sets for those ids and you can access those record in ``self`` https://github.com/odoo/odoo/blob/10.0/addons/purchase/models/purchase.py#L338

You can also check payload via calling **Confirm Order** from Browser and inspect request.
The valid request payload when Confirming order via browser:

```json
{
   "jsonrpc":"2.0",
   "method":"call",
   "params":{
      "model":"purchase.order",
      "method":"button_confirm",
      "args":[
         [23],
         {
            "lang":"en_US",
            "tz":"Europe/Brussels",
            "uid":1,
            "search_default_todo":1,
            "params":{
               "action":830
            }
         }
      ]
   },
   "id":112869814
}
```
We can ignore user context details but you need to pass second parameter as required so we can use empty json object.

Hope, this will solve your issue.

Thanks.

**Comment by pranasabda** [comment]
Hello, @bunny-oogbox  thanks for your answer it solved my problem, Awesome! thank you very much.  :+1: 

Note: I try using PO_id as float type and it works fine too :+1: 

Thanks

**Comment by bunny-oogbox** [comment]
Great 👍
