### ISSUE TITLE
how to use multiple condition search.Read condition

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile-api#9]
how can we set single field  multiple conditions to filter in domain? 

Example: its not working ,
   domain.add("state", "=", "draft");
   domain.add("state", "=", "rejected");
   domain.add("state", "=", "approved");

**Comment by bunny-oogbox** [comment]
Hello,
You can use ``in`` operator with list of values to check

```java
domain.add("state", "in", Arrays.asList("draft", "rejected", "approved"));

**Comment by cviacmob** [comment]
Its work ,thanks for your help..
